Marcus-Johnson/NJInsurancePlatform

NJInsurancePlatform/Models/Bill.cs
=> Cenj 8 model bill addition one

NJInsurancePlatform/Controllers/BillController.cs
Also added imports we will most likely need later
=> Created the BillController.cs file

NJInsurancePlatform/Controllers/CustomerController.cs
=> Customer Controller

.github/workflows/codeql.yml
Verifies code in flow can run in Environment without errors.
=> CENJ-37-git-hub-code-ql-cross-examinations-of-c-js-crashing

NJInsurancePlatform/Controllers/PaymentController.cs
=> CENJ-30 Added Payment Controller File to Controller folder

NJInsurancePlatform/Views/Shared/_Layout.cshtml
using default values. background-color also changed
=> CENJ-40 Init navbar addition

NJInsurancePlatform/Controllers/PolicyController.cs, NJInsurancePlatform/Views/Policy/PolicyDetails.cshtml, NJInsurancePlatform/Views/PolicyDetails.cshtml, NJInsurancePlatform/Views/Shared/_Layout.cshtml
=> Cenj 33 addition policy details view containing wireframe

NJInsurancePlatform/Controllers/CustomerController.cs, NJInsurancePlatform/Views/Customer/Details.cshtml, NJInsurancePlatform/Views/Shared/_Layout.cshtml
=> Created a 'My Profile' view and added link to navbar

NJInsurancePlatform/Interfaces/BillRepository.cs, NJInsurancePlatform/Interfaces/iBillRepository.cs, NJInsurancePlatform/Models/Bill.cs
added the bill repository
fixed a few issues in the iBillRepository file
fixed an issue in the Bill.cs model
=> Added the billRepository file

NJInsurancePlatform/Repositories/CustomerRepository.cs, NJInsurancePlatform/Repositories/ICustomerRepository.cs
These files are CENJ-57 and CENJ-62
=> Cenj 57 addition add icustomer repository interface to codebase

NJInsurancePlatform/Views/Administration/EditRole.cshtml, NJInsurancePlatform/Views/Administration/EditUsersInRole.cshtml, NJInsurancePlatform/Views/Administration/GetRoles.cshtml
added checkbox fix for roles and added functionality as well as button UI fix
=> init checkbox fix and cancel button color fix

NJInsurancePlatform/Interfaces/BeneficiaryRepository.cs, NJInsurancePlatform/Interfaces/BillRepository.cs, NJInsurancePlatform/Interfaces/CustomerRepository.cs, NJInsurancePlatform/Interfaces/ICustomerRepository.cs, NJInsurancePlatform/Interfaces/PolicyRepository.cs, NJInsurancePlatform/Interfaces/iBeneficiaryRepository.cs, NJInsurancePlatform/Interfaces/iPaymentRepository.cs, NJInsurancePlatform/Interfaces/iPolicyRepository.cs
Added missing IDisposable to all interface files, removed repository folders and moved 2 files to the interface folder.
=> IDisposable / Repository Folder

NJInsurancePlatform/Models/Beneficiary.cs
New attribute in Beneficiary model
=> Added CustomerMUID attribute

NJInsurancePlatform/Models/Claim.cs
=> Created Claim Model

NJInsurancePlatform/Views/Policy/PolicyDetails.cshtml
made changes to fix rows and added margin
=> CENJ-104-policy-details-view-input-field-text-elements-overlapping

NJInsurancePlatform/Controllers/CustomerController.cs, NJInsurancePlatform/Views/Customer/Claim.cshtml
=> Cenj 106 addition claim view containing wireframe

NJInsurancePlatform/Views/Home/Login.cshtml
- adjust fixed dimensions of login box
- fix distortion when validation messages are present
=> BugFix loginbox distortion when validation message is present

NJInsurancePlatform/Views/Customer/Claim.cshtml
Claim form implemented with CSS Grid;
=> Cenj 117 revision claim view changes

NJInsurancePlatform/Views/Home/ForgotPassword.cshtml
forgot password page now mirros login page.
white space has been lessened.
=> Matched forgot to login page. removed white space

NJInsurancePlatform/Models/FAQ.cs
=> CENJ-127 -model-faq  CENJ-128-addition-add-faq-model-to-codebase

NJInsurancePlatform/Data/InsuranceCorpDbContext.cs, NJInsurancePlatform/Migrations/20221111220118_initialmigration.Designer.cs, NJInsurancePlatform/Migrations/20221111220118_initialmigration.cs, NJInsurancePlatform/Models/AccountManager.cs
migrations for policy, customer, beneficiary, and admin
=> added migrations

NJInsurancePlatform/Controllers/Administration.cs, NJInsurancePlatform/Views/Administration/NoPaymentsComplete.cshtml, NJInsurancePlatform/Views/Administration/PaidTransactions.cshtml, NJInsurancePlatform/Views/Administration/UpdateRecorded.cshtml
=> add "Paid" actions and views

NJInsurancePlatform/Views/Administration/AllPaymentsComplete.cshtml, NJInsurancePlatform/Views/Administration/CreateRole.cshtml, NJInsurancePlatform/Views/Administration/EditRole.cshtml, NJInsurancePlatform/Views/Administration/EditUsersInRole.cshtml, NJInsurancePlatform/Views/Administration/GetRoles.cshtml, NJInsurancePlatform/Views/Administration/NoPaymentsComplete.cshtml, NJInsurancePlatform/Views/Administration/PaidTransactions.cshtml, NJInsurancePlatform/Views/Administration/UnpaidTransactions.cshtml, NJInsurancePlatform/Views/Administration/UpdateRecorded.cshtml, NJInsurancePlatform/Views/Customer/Claim.cshtml, NJInsurancePlatform/Views/Customer/MyPage.cshtml, NJInsurancePlatform/Views/Home/FAQ.cshtml, NJInsurancePlatform/Views/Home/ForgotPassword.cshtml, NJInsurancePlatform/Views/Home/Index.cshtml, NJInsurancePlatform/Views/Home/Login.cshtml, NJInsurancePlatform/Views/Home/Register.cshtml, NJInsurancePlatform/Views/Home/SignUp.cshtml, NJInsurancePlatform/Views/Payment/Details.cshtml, NJInsurancePlatform/Views/Payment/MakePayment.cshtml, NJInsurancePlatform/Views/Policy/PolicyDetails.cshtml, NJInsurancePlatform/Views/Policy/PolicyRequest.cshtml, NJInsurancePlatform/Views/Shared/_Layout.cshtml
- added a title to each page and made it dynamic for the header to change depending on the page title
- added dynamic welcome page to say hello to the name of the user logged in as well as  My Profile on the navbar changing to logged in users name
- removed the semicolon at the end of the layout page
- removed script tag in faq as it is been ran from local js file
see Jira for pic references
=> Dynamic Header/My Profile

NJInsurancePlatform/Views/Administration/AccessDenied.cshtml
added style to disable nav and footer
=>  CENJ-134-addition-access-denied-page-missing-content-changes

NJInsurancePlatform/Interfaces/BeneficiaryRepository.cs, NJInsurancePlatform/Interfaces/BillRepository.cs, NJInsurancePlatform/Interfaces/CustomerRepository.cs, NJInsurancePlatform/Interfaces/GroupRoomMessageRepository.cs, NJInsurancePlatform/Interfaces/PaymentRepository.cs, NJInsurancePlatform/Interfaces/PolicyRepository.cs, NJInsurancePlatform/Interfaces/TransactionRepository.cs
* All Repository Actions added for Dispose Implementation
* Whats still missing: Usage of `protected override void Dispose(bool disposing)` in ALL Controllers @lancecordel
=> Cenj 132 bug dispose method implementation not recognized patch3

NJInsurancePlatform/Data/InsuranceCorpDbContext.cs, NJInsurancePlatform/InterfaceImplementation/iRoomRepository.cs, NJInsurancePlatform/Interfaces/BeneficiaryRepository.cs, NJInsurancePlatform/Interfaces/BillRepository.cs, NJInsurancePlatform/Interfaces/CustomerRepository.cs, NJInsurancePlatform/Interfaces/GroupRoomMessageRepository.cs, NJInsurancePlatform/Interfaces/PaymentRepository.cs, NJInsurancePlatform/Interfaces/PolicyRepository.cs, NJInsurancePlatform/Interfaces/RoomRepository.cs, NJInsurancePlatform/Interfaces/TransactionRepository.cs
added i room interface and implementation. it seems currently the implementation has an issue under dispose where context does not exist
=>  CENJ-150-addition-add-i-room-repository-interface-to-codebase +151

NJInsurancePlatform/Data/InsuranceCorpDbContext.cs, NJInsurancePlatform/InterfaceImplementation/ICustomerRepository.cs, NJInsurancePlatform/InterfaceImplementation/iBeneficiaryRepository.cs, NJInsurancePlatform/InterfaceImplementation/iBillRepository.cs, NJInsurancePlatform/InterfaceImplementation/iGroupRoomMessageRepository.cs, NJInsurancePlatform/InterfaceImplementation/iPaymentRepository.cs, NJInsurancePlatform/InterfaceImplementation/iPolicyRepository.cs, NJInsurancePlatform/InterfaceImplementation/iRoomRepository.cs, NJInsurancePlatform/InterfaceImplementation/iTransactionRepository.cs, NJInsurancePlatform/Interfaces/BeneficiaryRepository.cs, NJInsurancePlatform/Interfaces/BillRepository.cs, NJInsurancePlatform/Interfaces/CustomerRepository.cs, NJInsurancePlatform/Interfaces/GroupRoomMessageRepository.cs, NJInsurancePlatform/Interfaces/PaymentRepository.cs, NJInsurancePlatform/Interfaces/PolicyRepository.cs, NJInsurancePlatform/Interfaces/RoomRepository.cs, NJInsurancePlatform/Interfaces/TransactionRepository.cs, NJInsurancePlatform/Views/Shared/_Layout.cshtml, NJInsurancePlatform/Views/_ViewImports.cshtml
- Fixed database context spelling error causing i dispose fix to continue throwing errors
=> I dispose database context spelling corrections

NJInsurancePlatform/Controllers/ClaimController.cs
=> ClaimController Added

NJInsurancePlatform/Data/InsuranceCorpDbContext.cs, NJInsurancePlatform/InterfaceImplementation/iFaqRepository.cs, NJInsurancePlatform/Interfaces/FaqRepository.cs
added interface and implementation
=> CENJ-161-addition-add-i-faq-repository-interface-to-codebase + 162

NJInsurancePlatform/Views/Home/Index.cshtml, NJInsurancePlatform/Views/Home/Login.cshtml, NJInsurancePlatform/Views/Home/Message.cshtml, NJInsurancePlatform/Views/Policy/PolicyRequest.cshtml, NJInsurancePlatform/Views/Shared/_Layout.cshtml, NJInsurancePlatform/wwwroot/css/site.css
- added gx image to navbar
- message icon redirects you to mesasge page
- reworked message page
=> Message Page Rework

NJInsurancePlatform/Data/InsuranceCorpDbContext.cs, NJInsurancePlatform/Migrations/20221122151435_added policy request.Designer.cs, NJInsurancePlatform/Migrations/20221122151435_added policy request.cs, NJInsurancePlatform/Models/PolicyRequest.cs
Update Migration File
Add Policy Request Table
=> CENJ-177-addition-add-a-policy-request-model

NJInsurancePlatform/Views/Policy/PolicyRequest.cshtml
added GalaxE colors to the page to make it look like a GalaxE product.
added shadows to text and boxes. 
centered the component for webpage and mobile.
plus various other tweaks for margins, padding, and so on.
=> finished styling the page to make it look professional

NJInsurancePlatform/Controllers/GroupRoomController.cs, NJInsurancePlatform/Controllers/HomeController.cs, NJInsurancePlatform/Models/MessagesViewModel.cs, NJInsurancePlatform/Views/Customer/MyPage.cshtml
- init commit
- not fully functional, but app is still operational
=> CENJ-154: Messages Addition

NJInsurancePlatform/Controllers/HomeController.cs, NJInsurancePlatform/Models/SignUpViewModel.cs, NJInsurancePlatform/Views/Administration/UnpaidTransactions.cshtml, NJInsurancePlatform/Views/Home/SignUp.cshtml
- Implement Form Validation On All Fiels
- Implement SSN Format Validation
- Implement Phone Number Format Validation
- Implement Gender Radio Button Selection
- Implement isPrimaryHolder Radio Button Selection
=> CENJ-181 addition: add form validation

NJInsurancePlatform/Data/InsuranceCorpDbContext.cs
this PR is a part of the overall ticket CENJ-160
=> added a few Faqs into the DB to work with during ticket CENJ-160

NJInsurancePlatform/Controllers/HomeController.cs, NJInsurancePlatform/Interfaces/FaqRepository.cs, NJInsurancePlatform/Program.cs, NJInsurancePlatform/Views/Home/FAQ.cshtml
Part of the overall ticket CENJ-160.
=> Faq page now populates with FAQs from DB

NJInsurancePlatform/Controllers/HomeController.cs, NJInsurancePlatform/Interfaces/FaqRepository.cs, NJInsurancePlatform/Views/Home/FAQ.cshtml
Still need to restrict its functionality to only Admin, but it is currently functional.
=> Delete FAQ now functions and is useable

NJInsurancePlatform/Controllers/HomeController.cs, NJInsurancePlatform/Views/Home/CreateFAQ.cshtml
can be created on page: /Home/CreateFAQ
=> Admin can now create FAQs

NJInsurancePlatform/Controllers/Administration.cs, NJInsurancePlatform/Controllers/GroupRoomController.cs, NJInsurancePlatform/Data/InsuranceCorpDbContext.cs, NJInsurancePlatform/Views/Administration/TransactionSearchResults.cshtml, NJInsurancePlatform/Views/Administration/UpdateRecorded.cshtml, NJInsurancePlatform/Views/GroupRoom/Message.cshtml, NJInsurancePlatform/appsettings.json, NJInsurancePlatform/wwwroot/css/site.css, NJInsurancePlatform/wwwroot/js/site.js
=> Cenj 183 bug when room has no messages send button does not appear

NJInsurancePlatform/Views/Customer/Index.cshtml, NJInsurancePlatform/Views/GroupRoom/Message.cshtml, NJInsurancePlatform/Views/Shared/_Layout.cshtml, NJInsurancePlatform/appsettings.json, NJInsurancePlatform/wwwroot/css/Message.css
- Make user chat bubble appear to the right
- Other chat bubbles appear to the left
- make User chatbox grey, and others blue
- Name appears above the chat bubble
- time stamp appears below the chat bubble
=> Cenj 186 revision add sender name to message when sent

NJInsurancePlatform/Views/GroupRoom/Message.cshtml, NJInsurancePlatform/Views/Home/Login.cshtml, NJInsurancePlatform/Views/Shared/_Layout.cshtml, NJInsurancePlatform/wwwroot/css/Message.css, NJInsurancePlatform/wwwroot/js/site.js
- lengthen username and password input fields
=> CENJ-188-bug-login-username-and-password-input-box-too-short

NJInsurancePlatform/Controllers/AdministrationController.cs
I am fairly certain this is the correct fix to the issue.  BUT main currently has build errors so I cannot test this out yet
=> EditUsersInRole fixed

NJInsurancePlatform/Controllers/AdministrationController.cs
seems like a merge conflict was causing errors in my previous pull request.  Attempt to fix.
=> Error correction in main branch.

NJInsurancePlatform/Controllers/Administration.cs, NJInsurancePlatform/Controllers/AdministrationController.cs, NJInsurancePlatform/Controllers/CustomerController.cs, NJInsurancePlatform/Controllers/GroupRoomController.cs, NJInsurancePlatform/Controllers/HomeController.cs, NJInsurancePlatform/Controllers/PaymentController.cs, NJInsurancePlatform/Controllers/PolicyController.cs, NJInsurancePlatform/Views/Administration/AccessDenied.cshtml, NJInsurancePlatform/Views/Administration/GetRoles.cshtml, NJInsurancePlatform/Views/Customer/Index.cshtml, NJInsurancePlatform/Views/Home/FAQ.cshtml, NJInsurancePlatform/Views/Shared/_Layout.cshtml
=> Activate Authorization accross Entire App and other touch ups with css

NJInsurancePlatform/Views/Customer/Index.cshtml, NJInsurancePlatform/wwwroot/css/site.css
The tabs would retain their white background in darkmode, so I fixed it that it changes to a dark color to match the dark theme.
=> fixed an issue on customer page where darkmode looked odd in tabs

NJInsurancePlatform/Controllers/CustomerController.cs, NJInsurancePlatform/Views/Customer/CustomerPolicyRequest.cshtml, NJInsurancePlatform/Views/Customer/Index.cshtml, NJInsurancePlatform/Views/Payment/MakePayment.cshtml, NJInsurancePlatform/Views/Policy/PolicyRequest.cshtml, NJInsurancePlatform/wwwroot/css/site.css
- create a ternary to update mandatory payment in payment view based on balance.  If minimum payment exceeds 
Balance, balance is required, else minimum payment is required
- Add Dollar signs in beginning of monetary values in payment view
=> Minor adjustments2

NJInsurancePlatform/Controllers/CustomerController.cs, NJInsurancePlatform/Views/Customer/CustomerPolicyRequest.cshtml, NJInsurancePlatform/Views/Customer/Index.cshtml, NJInsurancePlatform/Views/Payment/MakePayment.cshtml, NJInsurancePlatform/Views/Policy/PolicyRequest.cshtml, NJInsurancePlatform/wwwroot/css/site.css
- Sort Transactions by date before displaying in UI
- change z index of footer to bring to the front to prevent overlap of other components
- added spacing to bottoms of UI div components to prevent footer overlap
=> Minor adjusments
